#!/usr/bin/env python3
"""
pins.py — Pinterest pin renderer (1000x1500, the 2:3 format Pinterest favors).

Each pin shows a REAL mini word-search grid (generated by the KDP engine) with a
couple of words pre-highlighted, so the product is obvious at thumbnail size.
Five headline variants per theme; palette per niche. Clean editorial look —
no doodles, no clip art.

    /usr/bin/python3 pins.py --themes ../kdp/themes/animals.json --outdir out/animals/pins
"""
import argparse, json, os, random, string, sys

KDP_DIR = os.environ.get("KDP_DIR") or os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "kdp")
if not os.path.isdir(KDP_DIR):  # live dir moved; fall back to the canonical KDP engine location
    KDP_DIR = os.path.expanduser("~/Desktop/clauwork/kdp")
sys.path.insert(0, KDP_DIR)
import wordsearch as ws  # noqa: E402

from PIL import Image, ImageDraw, ImageFont  # noqa: E402

W, H = 1000, 1500
SUP = "/System/Library/Fonts/Supplemental/"
F_SERIF_B = SUP + "Georgia Bold.ttf"
F_SANS_B = SUP + "Arial Bold.ttf"
F_SANS = SUP + "Arial.ttf"
F_MONO_B = SUP + "Courier New Bold.ttf"

# (bg, band, accent, ink) per niche — calm, giftable, high-contrast at thumbnail size
PALETTES = {
    "animals":   ("#f6f3ea", "#2c4f3b", "#e0a458", "#1d1d1b"),
    "nature":    ("#f2f5ee", "#3a5a40", "#a3b18a", "#1d1d1b"),
    "food":      ("#fdf6ec", "#9c3d2e", "#e8b04b", "#241a14"),
    "bible":     ("#f4f4f8", "#2b3a67", "#c8a24a", "#181c28"),
    "christmas": ("#faf4ec", "#9b2226", "#2c5f2d", "#231414"),
    "usa":       ("#f5f5f3", "#1f3a63", "#b22234", "#15192b"),
    "kids":      ("#fffbef", "#1b6ca8", "#f6ae2d", "#1b2330"),
    "beach-vacation":  ("#fbf6ec", "#1f6f78", "#e8a23d", "#15252a"),
    "summer-vacation": ("#fff8ec", "#e07a3f", "#f3c34a", "#241a10"),
    "retro-travel-and-landmarks": ("#f4ecd8", "#2f6d72", "#d98a34", "#20312f"),
    "home-cooking-and-baking": ("#fdf3e6", "#8a4b2c", "#e0a53c", "#2a1c12"),
}
DEFAULT_PALETTE = ("#f6f3ea", "#2c4f3b", "#e0a458", "#1d1d1b")


def font(path, size):
    return ImageFont.truetype(path, size)


def _lum(hexcolor):
    h = hexcolor.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def wrap_to_width(draw, text, fnt, max_w):
    words, lines, cur = text.split(), [], ""
    for w in words:
        trial = (cur + " " + w).strip()
        if draw.textlength(trial, font=fnt) <= max_w:
            cur = trial
        else:
            if cur:
                lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    return lines


def mini_grid_image(theme_words, n=10, highlight_n=2, seed=0):
    """Render a real n×n puzzle as a PIL image, with a couple of words highlighted."""
    rnd = random.Random(seed)
    pool = [w for w in ws.clean_words(theme_words) if 4 <= len(w) <= n]
    rnd.shuffle(pool)
    words = pool[:6]
    random.seed(seed)
    grid, placements, placed = ws.generate_puzzle(words, N=n)

    cell = 64
    pad = 10
    size = n * cell + pad * 2
    img = Image.new("RGB", (size, size), "#ffffff")
    d = ImageDraw.Draw(img, "RGBA")

    # highlight a couple of placed words under the letters
    for cells in placements[:highlight_n]:
        (r0, c0), (r1, c1) = cells[0], cells[-1]
        x0, y0 = pad + c0 * cell + cell // 2, pad + r0 * cell + cell // 2
        x1, y1 = pad + c1 * cell + cell // 2, pad + r1 * cell + cell // 2
        d.line([(x0, y0), (x1, y1)], fill=(255, 199, 51, 150), width=int(cell * 0.78))
        rr = int(cell * 0.39)
        d.ellipse([x0 - rr, y0 - rr, x0 + rr, y0 + rr], fill=(255, 199, 51, 150))
        d.ellipse([x1 - rr, y1 - rr, x1 + rr, y1 + rr], fill=(255, 199, 51, 150))

    # faint gridlines
    for i in range(n + 1):
        x = pad + i * cell
        d.line([(x, pad), (x, size - pad)], fill="#dcdcdc", width=2)
        d.line([(pad, x), (size - pad, x)], fill="#dcdcdc", width=2)
    d.rectangle([pad, pad, size - pad, size - pad], outline="#3a3a3a", width=4)

    f = font(F_MONO_B, int(cell * 0.62))
    for r in range(n):
        for c in range(n):
            ch = grid[r][c] or rnd.choice(string.ascii_uppercase)
            bb = d.textbbox((0, 0), ch, font=f)
            cw, chh = bb[2] - bb[0], bb[3] - bb[1]
            d.text((pad + c * cell + (cell - cw) / 2 - bb[0],
                    pad + r * cell + (cell - chh) / 2 - bb[1]), ch, font=f, fill="#1c1c1c")
    return img, [w.title() for w in placed[:highlight_n]]


def headline_variants(data):
    title = data.get("title", "Word Search")
    n = len(data.get("puzzles", []))
    # Derive a clean theme label for the "{short} Word Search" headline. Strip the
    # "Word Search for X" form first (e.g. "Word Search for Kids" -> "Kids"); otherwise
    # a mid-string "Word Search" survives and doubles up ("Word Search for Kids Word
    # Search — Instant Download").
    short = title.replace("Large Print ", "").strip()
    for token in ("Word Search for ", "Word Search"):
        short = short.replace(token, "")
    short = short.strip(" —-") or title
    return [
        title,
        f"{n} Large-Print Puzzles to Print at Home",
        f"{short} Word Search — Instant Download",
        "Screen-Free Evenings Start Here",
        f"Print Tonight, Solve Tonight — {n} Puzzles",
    ]


def render_pin(data, palette, headline, seed, out_path, pill_text=None, cta_text=None):
    bg, band, accent, ink = palette
    n_puzzles = len(data.get("puzzles", []))
    all_words = [w for p in data["puzzles"] for w in p["words"]]

    img = Image.new("RGB", (W, H), bg)
    d = ImageDraw.Draw(img, "RGBA")

    # header band
    band_h = 330
    d.rectangle([0, 0, W, band_h], fill=band)
    f_eyebrow = font(F_SANS_B, 26)
    eyebrow = "INSTANT DOWNLOAD  •  PRINTABLE PDF"
    ew = d.textlength(eyebrow, font=f_eyebrow)
    eyebrow_fill = accent if _lum(accent) > 0.45 else bg  # stay readable on the dark band
    d.text(((W - ew) / 2, 52), eyebrow, font=f_eyebrow, fill=eyebrow_fill)

    f_head = font(F_SERIF_B, 64)
    lines = wrap_to_width(d, headline, f_head, W - 140)
    if len(lines) > 2:
        f_head = font(F_SERIF_B, 52)
        lines = wrap_to_width(d, headline, f_head, W - 140)
    y = 116 if len(lines) > 1 else 150
    for ln in lines:
        lw = d.textlength(ln, font=f_head)
        d.text(((W - lw) / 2, y), ln, font=f_head, fill="#ffffff")
        y += f_head.size + 12

    # white card with the real puzzle preview (grid + word chips both INSIDE it)
    pad_in, gsize, chip_h = 55, W - 140 - 150, 52
    card_top = band_h + 70
    card = (70, card_top, W - 70, card_top + pad_in + gsize + 24 + chip_h + 40)
    d.rounded_rectangle([card[0] + 10, card[1] + 14, card[2] + 10, card[3] + 14],
                        radius=28, fill=(0, 0, 0, 28))
    d.rounded_rectangle(card, radius=28, fill="#ffffff", outline="#e3ded2", width=2)

    grid_img, shown_words = mini_grid_image(all_words, n=10, seed=seed)
    grid_img = grid_img.resize((gsize, gsize), Image.LANCZOS)
    img.paste(grid_img, (card[0] + (card[2] - card[0] - gsize) // 2, card_top + pad_in))

    # word chips under the grid
    f_chip = font(F_SANS_B, 30)
    chip_y = card_top + pad_in + gsize + 24
    labels = ["FIND:"] + shown_words
    widths = [d.textlength(t, font=f_chip) + (0 if i == 0 else 44) for i, t in enumerate(labels)]
    x = (W - sum(widths) - 18 * (len(labels) - 1)) / 2
    for i, t in enumerate(labels):
        if i == 0:
            d.text((x, chip_y + 8), t, font=f_chip, fill=ink)
        else:
            tw = d.textlength(t, font=f_chip)
            d.rounded_rectangle([x, chip_y, x + tw + 44, chip_y + 52], radius=26,
                                fill=bg, outline=band, width=3)
            d.text((x + 22, chip_y + 8), t, font=f_chip, fill=band)
        x += widths[i] + 18

    # count pill overlapping card top
    pill_t = pill_text or f"{n_puzzles} PUZZLES  •  FULL SOLUTIONS"
    f_pill = font(F_SANS_B, 28)
    pw = d.textlength(pill_t, font=f_pill) + 70
    px = (W - pw) / 2
    py = card[1] - 33
    d.rounded_rectangle([px, py, px + pw, py + 66], radius=33, fill=accent)
    d.text((px + 35, py + 15), pill_t, font=f_pill,
           fill="#241a07" if _lum(accent) > 0.45 else "#ffffff")

    # footer
    f_cta = font(F_SANS_B, 34)
    cta = cta_text or "Print at Home  •  US Letter  •  Large Print"
    cw = d.textlength(cta, font=f_cta)
    d.text(((W - cw) / 2, H - 165), cta, font=f_cta, fill=ink)
    f_brand = font(F_SERIF_B, 30)
    brand = data.get("author", "Evergreen Puzzle Press")
    bw = d.textlength(brand, font=f_brand)
    d.line([(W / 2 - 70, H - 105), (W / 2 + 70, H - 105)], fill=accent, width=4)
    d.text(((W - bw) / 2, H - 85), brand, font=f_brand, fill=band)

    img.save(out_path, "PNG")
    return out_path


def build(themes_path, outdir, count=5):
    data = json.load(open(themes_path))
    slug = os.path.splitext(os.path.basename(themes_path))[0]
    palette = PALETTES.get(slug, PALETTES.get(data.get("palette"), DEFAULT_PALETTE))
    os.makedirs(outdir, exist_ok=True)
    heads = headline_variants(data)
    out = []
    for i in range(count):
        path = os.path.join(outdir, f"pin_{i+1:02d}.png")
        render_pin(data, palette, heads[i % len(heads)], seed=100 + i * 7, out_path=path)
        out.append({"file": path, "headline": heads[i % len(heads)]})
        print(f"PIN  -> {path}")
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--themes", required=True)
    ap.add_argument("--outdir", required=True)
    ap.add_argument("--count", type=int, default=5)
    a = ap.parse_args()
    build(a.themes, a.outdir, a.count)


if __name__ == "__main__":
    main()
